$(document).ready(function(){
    
$('.show-login').click(function(e){
        e.preventDefault();
        $($('#login')[0]).show();
    });
    $('.close').click(function(e){
        $('.masc:visible').hide();
    });
    $('#show-registro').click(function(e){
        e.preventDefault();
        $($('#registro')[0]).show();
    });
       $('#show-contactar').click(function(e){
        e.preventDefault();
        $($('#contactar')[0]).show();
    });
    $('#show-publicar-curso').click(function(e){
        e.preventDefault();
        $($('#publicar-curso')[0]).show();
    });
    $('#show-publicar-duda').click(function(e){
        e.preventDefault();
        $($('#publicar-duda')[0]).show();
    });
    $('#show-modificar-curso').click(function(e){
        e.preventDefault();
        $($('#modificar-curso')[0]).show();
    });
    $('#show-valorar').click(function(e){
        e.preventDefault();
        $($('#valorar')[0]).show();
    });
     $('.show-gracias-curso').click(function(e){
        e.preventDefault();
        $($('#gracias-curso')[0]).show();
    });
    $('.show-gracias-duda').click(function(e){
        e.preventDefault();
        $($('#gracias-duda')[0]).show();
    });
     $('.show-gracias-contactar').click(function(e){
        e.preventDefault();
        $($('#gracias-contactar')[0]).show();
    });
       $('.show-recuperar').click(function(e){
        e.preventDefault();
        $($('#recuperar')[0]).show();
    });
     $('.show-registro-curso').click(function(e){
        e.preventDefault();
        $($('#registro-curso')[0]).show();
    });
     $('.show-registro-duda').click(function(e){
        e.preventDefault();
        $($('#registro-duda')[0]).show();
    });
      $('.show-registro-contactar').click(function(e){
        e.preventDefault();
        $($('#registro-contactar')[0]).show();
    });
      $('.show-login-curso').click(function(e){
        e.preventDefault();
        $($('#login-curso')[0]).show();
    });
      $('.show-login-duda').click(function(e){
        e.preventDefault();
        $($('#login-duda')[0]).show();
    });
      $('.show-login-contactar').click(function(e){
        e.preventDefault();
        $($('#login-contactar')[0]).show();
    });
    })